
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 25;
  public static final int EXIT = 9;
  public static final int AND = 2;
  public static final int READ = 14;
  public static final int NE = 21;
  public static final int LT = 17;
  public static final int ELSE = 12;
  public static final int PLUS = 23;
  public static final int INT = 30;
  public static final int RPAREN = 29;
  public static final int OR = 3;
  public static final int THEN = 11;
  public static final int SEMI = 22;
  public static final int NOT = 4;
  public static final int END = 8;
  public static final int TRUE = 5;
  public static final int IF = 10;
  public static final int LPAREN = 28;
  public static final int GT = 19;
  public static final int ID = 32;
  public static final int LE = 18;
  public static final int WRITE = 13;
  public static final int BEGIN = 7;
  public static final int STRING = 33;
  public static final int EOF = 0;
  public static final int DIVIDE = 26;
  public static final int MINUS = 24;
  public static final int GE = 20;
  public static final int FALSE = 6;
  public static final int error = 1;
  public static final int ASSIGN = 15;
  public static final int EQ = 16;
  public static final int MODE = 27;
  public static final int DOUBLE = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "OR",
  "NOT",
  "TRUE",
  "FALSE",
  "BEGIN",
  "END",
  "EXIT",
  "IF",
  "THEN",
  "ELSE",
  "WRITE",
  "READ",
  "ASSIGN",
  "EQ",
  "LT",
  "LE",
  "GT",
  "GE",
  "NE",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MODE",
  "LPAREN",
  "RPAREN",
  "INT",
  "DOUBLE",
  "ID",
  "STRING"
  };
}

